"""Create users table

Revision ID: de5bb5e0c1ee
Revises: ad26aa7aeec8
Create Date: 2025-03-31 12:14:43.424630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5bb5e0c1ee'
down_revision: Union[str, None] = 'ad26aa7aeec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
