"""Create users table

Revision ID: f23cbeca2ac5
Revises: de5bb5e0c1ee
Create Date: 2025-04-08 16:37:40.707801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23cbeca2ac5'
down_revision: Union[str, None] = 'de5bb5e0c1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
